version: "3.5"

services: 
    db:
        image: postgres
        hostname: omop-viewer-db
        environment:
            - POSTGRES_DB=omop
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust
        build:
                context: .
                dockerfile: ./db/Dockerfile
        #network_mode: bridge
        networks:
            - djangonetwork
        command: postgres -c max_wal_size=2GB -c work_mem=50MB -c autovacuum=off     
        expose:
            - "5432"

    app:
        hostname: omop-viewer-app
        restart: always
        build:
            context: .
            dockerfile: ./app/Dockerfile
        #network_mode: bridge
        networks:
            - djangonetwork
        links: 
            - "db:omop-viewer-db"
        ports:
            - "5599:8000"
        depends_on:
            - db
        environment:
            WAIT_HOSTS: db:5432
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"

networks:
    djangonetwork:
        driver: bridge


    
