version: "3.5"

services: 
    db:
        image: postgres
        hostname: omop-viewer-db
        build:
                context: ./db
                dockerfile: Dockerfile
        environment:
            - POSTGRES_DB=omop
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust
        networks:
            - djangonetwork
        expose:
            - "5432"

    webapp:
        hostname: omop-viewer-webapp
        restart: always
        build:
            context: ./webapp
            dockerfile: Dockerfile
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_DB=omop
            - POSTGRES_SCHEMA=cdm_synthea10
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - djangonetwork
        links: 
            - "db:omop-viewer-db"
        ports:
            - "5599:8000"
        depends_on:
            - db

networks:
    djangonetwork:
        driver: bridge
