# Generated by Django 3.1 on 2020-08-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omop_viewer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
