FROM postgres
LABEL Guannan Gong <guannan.gong@yale.edu>

RUN mkdir /omop
COPY ./data/omop/ /omop
WORKDIR /omop

RUN apt-get update
RUN apt-get upgrade
RUN apt-get install wget

# Download omop sql dump files to /omop
RUN wget https://cch-omop-viewer.s3.amazonaws.com/synthea_omop_a{a..j}.sql

# Re-construct the original omop sql dump file
RUN cat synthea_omop_**.sql > /docker-entrypoint-initdb.d/synthea_omop_dump.sql